pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {
        stage('Build Project') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn test'
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml'
        }
    }
}